### ISSUE TITLE
Not working with nvim-treesitter

### ISSUE THREAD

**Issue by ram02z** [krnik/tree-sitter-fish#1]
Hey,

I know that this parser is not as mature as the other tree sitter parsers I have seen. However, I cannot seem to get it to work on nvim-treesitter. Is it ready for use or is it still under development?

Thanks.

**Comment by ram02z** [comment]
Nevermind, I am just misinformed.
There is a PR at https://github.com/nvim-treesitter/nvim-treesitter/issues/1268 though.

**Comment by krnik** [comment]
Basically you'd have to [add parser](https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers).
As for the highlighting I'll follow up this evening with intstructions.

**Comment by krnik** [comment]
I see that you've figured out how to add queries so that `nvim-treesitter` sees them: https://github.com/nvim-treesitter/nvim-treesitter/issues/1268#issuecomment-830676648

But for anyone else wondering how to use it with `nvim-treesitter` for now until this parser lands in their repo, this is the relevant docs:
> ### Adding queries
> Queries are what nvim-treesitter uses to extract informations from the syntax tree; they are located in the `queries/{language}/*` runtime directories (like the queries folder of this plugin), e.g., `queries/{language}/{locals,highlights,textobjects}.scm`. Other modules may require additional queries such as `folding.scm`.

Which means you should add the `highlights.scm` for `fish` into the `runtimepath`, for example next to the `init.vim` file
```
init.vim
queries/
  fish/
      highlights.scm
      indent.scm
```

**Comment by ram02z** [comment]
@krnik Thanks! I have managed to get the highlight scheme extended and include other schemes. The PR is here https://github.com/nvim-treesitter/nvim-treesitter/pull/1272.
